CREATE TABLE [dbo].[Owner]
(
	[ID] INT IDENTITY NOT NULL,
	[LastName] NVARCHAR (60) NOT NULL,
	[FirstName] NVARCHAR (60) NOT NULL,
	[BirthDate] DATETIME2 NOT NULL,
	[Email] NVARCHAR (60) NOT NULL,
	[HashPasswd] NVARCHAR(MAX) NOT NULL,
	[Salt] varbinary(16),
	[Score] INT DEFAULT 0,
	CHECK ([Score] BETWEEN 0 AND 5),
	CONSTRAINT [PK_Owner] PRIMARY KEY ([ID])	
)
