CREATE TABLE [dbo].[Pet]
(
	[ID] INT IDENTITY NOT NULL,
	[ID_Owner] INT NOT NULL,
	[NickName] NVARCHAR(60) NOT NULL,
	[Type] NVARCHAR(20) NOT NULL,
	[Breed] NVARCHAR (20),
	[BirthDate] DATETIME2 NOT NULL,
	CONSTRAINT [PK_Pet] PRIMARY KEY ([ID]),
	CONSTRAINT [FK_OwnerPet] FOREIGN KEY ([ID_Owner]) REFERENCES Owner([ID])
)
